describe('landing page',()=>{
    it('should land homepage',()=>{
        cy.visit('http://zero.webappsecurity.com/login.html')
        cy.wait(5000)
        cy.get('[id=user_login]').type('username')
        cy.get('[id=user_password]').type('password')
        cy.get('[value=Sign in]').click()
        cy.get('#onlineBankingMenu').click()
        //cy.get('[id=online-banking]').click()
        cy.wait(5000)
        cy.get('a:contains("Zero Bank")').click()
        cy.url().should('include','index')
        cy.get('[id=online-banking]').click()
        cy.get('[id=account_summary_link]').click()
        //cy.url().should('include','account-summary')
        cy.wait(5000)
        cy.get('a:contains("Brokerage")').click()
        cy.url().should('include','accountId=6')
    })
})